#!/bin/sh
set -e

case "$1" in
    help|-h|--help)
        printf >&2 '%s\n' \
            'usage: gen-efikeys [output-dir]'
        exit 1
    ;;
    '') ;;
    *)
        cd "$1" || exit 1
    ;;
esac

NAME="$USER@$(hostname --fqdn)"

openssl req \
    -new -x509 -newkey rsa:2048 \
    -subj "/CN=$NAME PK/" \
    -days 3650 \
    -nodes -sha256 \
    -keyout PK.key \
    -out PK.crt

openssl req -new -x509 -newkey rsa:2048 \
    -subj "/CN=$NAME KEK/" \
    -days 3650 \
    -nodes -sha256 \
    -keyout KEK.key \
    -out KEK.crt

openssl req \
    -new -x509 -newkey rsa:2048 \
    -subj "/CN=$NAME DB/" \
    -days 3650 \
    -nodes -sha256 \
    -keyout db.key \
    -out db.crt

chmod 0600  -- *.key

GUID="$(cat /proc/sys/kernel/random/uuid)"
printf '%s\n' "$GUID" > guid.uuid

cert-to-efi-sig-list -g "$GUID" \
    PK.crt PK.esl
sign-efi-sig-list \
    -k PK.key -c PK.crt \
    PK PK.esl \
    PK.auth

cert-to-efi-sig-list -g "$GUID" \
    KEK.crt KEK.esl
sign-efi-sig-list -a \
    -k PK.key -c PK.crt \
    KEK KEK.esl \
    KEK.auth

cert-to-efi-sig-list -g "$GUID" \
    db.crt db.esl
sign-efi-sig-list -a \
    -k KEK.key -c KEK.crt \
    db db.esl \
    db.auth
