#!/bin/sh
# Copyright (c) 2018, Anthony DeDominic <adedomin@gmail.com>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

die() {
    printf >&2 '%s\n' "Error: $*"
    exit 1
}
. /etc/bundle-kernel.conf ||
    die 'Failed to source configuration.'

bootctl --path="$ESP" update ||
    die 'Failed to update systemd-boot bootloader'

sbsign \
    --key "$SECUREBOOT_DBKEY" \
    --cert "$SECUREBOOT_DBCRT" \
    --output "$ESP"/EFI/systemd/systemd-bootx64.efi \
    "$ESP"/EFI/systemd/systemd-bootx64.efi ||
    die 'Failed to sign updated bootloader'
